version: 2

signs:
  - artifacts: checksum

project_name: spot
dist: .bin
builds:
  - id: spot
    binary: "spot"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    dir: cmd/spot
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

  - id: secrets
    binary: "spot-secrets"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    dir: cmd/secrets
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - id: spot
    name_template: >-
     {{.ProjectName}}_
     {{- .Tag}}_
     {{- if eq .Os "darwin"}}macos
     {{- else if eq .Os "windows"}}win
     {{- else}}{{.Os}}{{end}}_
     {{- if eq .Arch "amd64"}}x86_64
     {{- else if eq .Arch "386"}}i386
     {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - spot.1
      - completions/*


brews:
  -
    name: spot
    repository:
      owner: umputun
      name: homebrew-apps
      branch: master
    directory: Formula
    commit_author:
      name: umputun
      email: umputun@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://spotctl.com/"
    description: "Spot (aka spotctl) is a powerful and easy-to-use tool for effortless deployment and configuration management."
    license: "MIT"
    extra_install: |
      bash_completion.install "completions/spot.bash" => "spot"
      bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
      zsh_completion.install "completions/spot.zsh" => "_spot"
      zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
      fish_completion.install "completions/spot.fish" => "spot.fish"
      fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"

nfpms:
  - id: spot
    package_name: spot
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://spot.umputun.dev
    maintainer: Umputun <umputun@gmail.com>
    description: A collection of tools for the effortless deployment, configuration, and management of secrets
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
    release: 1
    contents:
      - src: completions/spot.bash
        dst: /usr/share/bash-completion/completions/spot
      - src: completions/spot-secrets.bash
        dst: /usr/share/bash-completion/completions/spot-secrets
      - src: completions/spot.zsh
        dst: /usr/share/zsh/vendor-completions/_spot
      - src: completions/spot-secrets.zsh
        dst: /usr/share/zsh/vendor-completions/_spot-secrets
      - src: completions/spot.fish
        dst: /usr/share/fish/vendor_completions.d/spot.fish
      - src: completions/spot-secrets.fish
        dst: /usr/share/fish/vendor_completions.d/spot-secrets.fish
