# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spot < Formula
  desc "Spot (aka simplotask) is a powerful and easy-to-use tool for effortless deployment and configuration management."
  homepage "https://simplotask.com/"
  version "0.14.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/spot/releases/download/v0.14.6/spot_v0.14.6_darwin_x86_64.tar.gz"
      sha256 "d13f1ae13ed6e94f23b2c662f3352578a5c0494d6426a60e93c60aad69eaaf64"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/spot/releases/download/v0.14.6/spot_v0.14.6_darwin_macos.tar.gz"
      sha256 "11f706999d0d1cb5a2c186da2a97659b83eb220f0fe4564f3c2cf5c61332ddd9"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v0.14.6/spot_v0.14.6_linux_arm.tar.gz"
      sha256 "3065ce20eea2f328ec7e8a9e3116691a1101711fa9971798a47e404c3dc8e61e"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umputun/spot/releases/download/v0.14.6/spot_v0.14.6_linux_x86_64.tar.gz"
      sha256 "dd36f2e5c2dab7f023404f5f4b7edc23d67400f42fbd360e8fb0686f4da9c943"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v0.14.6/spot_v0.14.6_linux_arm64.tar.gz"
      sha256 "c28222cab4248623721d11e43d5855dd124392af711700803c870f0f22b2f9b8"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
  end
end
