// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/ssm"
	"sync"
)

// SSMClientMock is a mock implementation of executor.SSMClient.
//
//	func TestSomethingThatUsesSSMClient(t *testing.T) {
//
//		// make and configure a mocked executor.SSMClient
//		mockedSSMClient := &SSMClientMock{
//			GetCommandInvocationFunc: func(ctx context.Context, params *ssm.GetCommandInvocationInput, optFns ...func(*ssm.Options)) (*ssm.GetCommandInvocationOutput, error) {
//				panic("mock out the GetCommandInvocation method")
//			},
//			SendCommandFunc: func(ctx context.Context, params *ssm.SendCommandInput, optFns ...func(*ssm.Options)) (*ssm.SendCommandOutput, error) {
//				panic("mock out the SendCommand method")
//			},
//		}
//
//		// use mockedSSMClient in code that requires executor.SSMClient
//		// and then make assertions.
//
//	}
type SSMClientMock struct {
	// GetCommandInvocationFunc mocks the GetCommandInvocation method.
	GetCommandInvocationFunc func(ctx context.Context, params *ssm.GetCommandInvocationInput, optFns ...func(*ssm.Options)) (*ssm.GetCommandInvocationOutput, error)

	// SendCommandFunc mocks the SendCommand method.
	SendCommandFunc func(ctx context.Context, params *ssm.SendCommandInput, optFns ...func(*ssm.Options)) (*ssm.SendCommandOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetCommandInvocation holds details about calls to the GetCommandInvocation method.
		GetCommandInvocation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *ssm.GetCommandInvocationInput
			// OptFns is the optFns argument value.
			OptFns []func(*ssm.Options)
		}
		// SendCommand holds details about calls to the SendCommand method.
		SendCommand []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *ssm.SendCommandInput
			// OptFns is the optFns argument value.
			OptFns []func(*ssm.Options)
		}
	}
	lockGetCommandInvocation sync.RWMutex
	lockSendCommand          sync.RWMutex
}

// GetCommandInvocation calls GetCommandInvocationFunc.
func (mock *SSMClientMock) GetCommandInvocation(ctx context.Context, params *ssm.GetCommandInvocationInput, optFns ...func(*ssm.Options)) (*ssm.GetCommandInvocationOutput, error) {
	if mock.GetCommandInvocationFunc == nil {
		panic("SSMClientMock.GetCommandInvocationFunc: method is nil but SSMClient.GetCommandInvocation was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *ssm.GetCommandInvocationInput
		OptFns []func(*ssm.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockGetCommandInvocation.Lock()
	mock.calls.GetCommandInvocation = append(mock.calls.GetCommandInvocation, callInfo)
	mock.lockGetCommandInvocation.Unlock()
	return mock.GetCommandInvocationFunc(ctx, params, optFns...)
}

// GetCommandInvocationCalls gets all the calls that were made to GetCommandInvocation.
// Check the length with:
//
//	len(mockedSSMClient.GetCommandInvocationCalls())
func (mock *SSMClientMock) GetCommandInvocationCalls() []struct {
	Ctx    context.Context
	Params *ssm.GetCommandInvocationInput
	OptFns []func(*ssm.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *ssm.GetCommandInvocationInput
		OptFns []func(*ssm.Options)
	}
	mock.lockGetCommandInvocation.RLock()
	calls = mock.calls.GetCommandInvocation
	mock.lockGetCommandInvocation.RUnlock()
	return calls
}

// SendCommand calls SendCommandFunc.
func (mock *SSMClientMock) SendCommand(ctx context.Context, params *ssm.SendCommandInput, optFns ...func(*ssm.Options)) (*ssm.SendCommandOutput, error) {
	if mock.SendCommandFunc == nil {
		panic("SSMClientMock.SendCommandFunc: method is nil but SSMClient.SendCommand was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *ssm.SendCommandInput
		OptFns []func(*ssm.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockSendCommand.Lock()
	mock.calls.SendCommand = append(mock.calls.SendCommand, callInfo)
	mock.lockSendCommand.Unlock()
	return mock.SendCommandFunc(ctx, params, optFns...)
}

// SendCommandCalls gets all the calls that were made to SendCommand.
// Check the length with:
//
//	len(mockedSSMClient.SendCommandCalls())
func (mock *SSMClientMock) SendCommandCalls() []struct {
	Ctx    context.Context
	Params *ssm.SendCommandInput
	OptFns []func(*ssm.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *ssm.SendCommandInput
		OptFns []func(*ssm.Options)
	}
	mock.lockSendCommand.RLock()
	calls = mock.calls.SendCommand
	mock.lockSendCommand.RUnlock()
	return calls
}
