// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/aws/aws-sdk-go-v2/service/ssm"
)

// SSMSessionClientMock is a mock implementation of executor.SSMSessionClient.
//
//	func TestSomethingThatUsesSSMSessionClient(t *testing.T) {
//
//		// make and configure a mocked executor.SSMSessionClient
//		mockedSSMSessionClient := &SSMSessionClientMock{
//			StartSessionFunc: func(ctx context.Context, params *ssm.StartSessionInput, optFns ...func(*ssm.Options)) (*ssm.StartSessionOutput, error) {
//				panic("mock out the StartSession method")
//			},
//		}
//
//		// use mockedSSMSessionClient in code that requires executor.SSMSessionClient
//		// and then make assertions.
//
//	}
type SSMSessionClientMock struct {
	// StartSessionFunc mocks the StartSession method.
	StartSessionFunc func(ctx context.Context, params *ssm.StartSessionInput, optFns ...func(*ssm.Options)) (*ssm.StartSessionOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// StartSession holds details about calls to the StartSession method.
		StartSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *ssm.StartSessionInput
			// OptFns is the optFns argument value.
			OptFns []func(*ssm.Options)
		}
	}
	lockStartSession sync.RWMutex
}

// StartSession calls StartSessionFunc.
func (mock *SSMSessionClientMock) StartSession(ctx context.Context, params *ssm.StartSessionInput, optFns ...func(*ssm.Options)) (*ssm.StartSessionOutput, error) {
	if mock.StartSessionFunc == nil {
		panic("SSMSessionClientMock.StartSessionFunc: method is nil but SSMSessionClient.StartSession was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *ssm.StartSessionInput
		OptFns []func(*ssm.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockStartSession.Lock()
	mock.calls.StartSession = append(mock.calls.StartSession, callInfo)
	mock.lockStartSession.Unlock()
	return mock.StartSessionFunc(ctx, params, optFns...)
}

// StartSessionCalls gets all the calls that were made to StartSession.
// Check the length with:
//
//	len(mockedSSMSessionClient.StartSessionCalls())
func (mock *SSMSessionClientMock) StartSessionCalls() []struct {
	Ctx    context.Context
	Params *ssm.StartSessionInput
	OptFns []func(*ssm.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *ssm.StartSessionInput
		OptFns []func(*ssm.Options)
	}
	mock.lockStartSession.RLock()
	calls = mock.calls.StartSession
	mock.lockStartSession.RUnlock()
	return calls
}
