// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// SecretsProviderMock is a mock implementation of config.SecretsProvider.
//
//	func TestSomethingThatUsesSecretsProvider(t *testing.T) {
//
//		// make and configure a mocked config.SecretsProvider
//		mockedSecretsProvider := &SecretsProviderMock{
//			GetFunc: func(key string) (string, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedSecretsProvider in code that requires config.SecretsProvider
//		// and then make assertions.
//
//	}
type SecretsProviderMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(key string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *SecretsProviderMock) Get(key string) (string, error) {
	if mock.GetFunc == nil {
		panic("SecretsProviderMock.GetFunc: method is nil but SecretsProvider.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSecretsProvider.GetCalls())
func (mock *SecretsProviderMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
